name: Build
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    container: archlinux:base-devel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: |
          pacman -Syu --noconfirm
          useradd build
      - name: Make package
        run: su build && makepkg -s
