name: Build
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    container: archlinux:base-devel
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: |
          pacman -Syu --noconfirm
          useradd build
          chown -R build .
      - name: Make package
        if: startsWith(github.ref, 'refs/tags/')
        run: su build -c "makepkg -s"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.pkg.*"
