name: Build
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    container: archlinux:base-devel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make package
        run: makepkg -s
